general:
  output_dir: ./results/resnet50/simclr/stl10
network:
  name: resnet50
  mlp_head:
    hidden_size: 512
    proj_size: 128
data:
  s: 1
  image_size: 89
  dataset: stl10
  num_classes: 10
  dataset_type: default
trainer:
  batch_size: 256
  epochs: 100
  num_workers: 4
optimizer:
  lr: 3.0e-4
  weight_decay: 10.0e-6
