general:
  output_dir: ./results/resnet50/barlow_twins-affine/tiny_imagenet/investigate-losses-bounded
network:
  algo: barlow_twins
  name: resnet50
  mlp_head:
    hidden_size: 512
    proj_size: 128
  pred_head:
    hidden_size: 512
    proj_size: 6
data:
  s: 1
  image_size: 64
  dataset: tiny_imagenet
  root: /mnt/data/home/david/data/tiny-imagenet
  num_classes: 100
  dataset_type: affine
  affine_type: bounded
trainer:
  batch_size: 256
  epochs: 100
  num_workers: 4
  device: cuda
  beta1: 1.0
  beta2: 10.0
optimizer:
  lr: 0.03
  weight_decay: 0.0004
