general:
  output_dir: ./results/resnet18/simclr/cifar100
data:
  dataset: cifar100
  max_shear: 25
  max_degrees: 90
  max_translate: 24
  min_scale: 0.7
  max_scale: 1.3
optim:
  lr: 3.0e-4
  weight_decay: 10.0e-6
  epochs: 100
model:
  hidden_dim: 512
  aggregation_strategy: concat
  backbone:
    name: resnet18
