general:
  output_dir: ./results/resnet50/simclr-affine/tiny_imagenet/concat
network:
  algo: simclr
  name: resnet50
  mlp_head:
    hidden_size: 512
    proj_size: 128
  pred_head:
    hidden_size: 512
    proj_size: 6
  aggregation_strategy: concat
data:
  s: 1
  image_size: 64
  dataset: tiny_imagenet
  root: /mnt/data/home/david/data/tiny-imagenet/tiny-imagenet-200
  num_classes: 100
  dataset_type: affine
trainer:
  batch_size: 256
  epochs: 100
  num_workers: 4
  device: cuda
optimizer:
  lr: 0.03
  weight_decay: 0.0004
