general:
  output_dir: ./results/resnet50/simclr-affine/tiny_imagenet/concat
network:
  algo: simclr
  name: resnet50
  mlp_head:
    hidden_size: 512
    proj_size: 128
data:
  s: 1
  image_size: 224
  dataset: food101
  root: /mnt/data/home/david/data/food/food-101
  num_classes: 101
  dataset_type: default
trainer:
  batch_size: 64
  epochs: 100
  num_workers: 4
  device: cuda
optimizer:
  lr: 0.03
  weight_decay: 0.0004
