general:
  output_dir: ./results/resnet18/simclr-affine/cifar10
network:
  name: resnet18
  mlp_head:
    hidden_size: 512
    proj_size: 128
  pred_head:
    hidden_size: 512
    proj_size: 6
data:
  s: 1
  image_size: 32
  dataset: cifar10
  num_classes: 10
  dataset_type: affine
trainer:
  batch_size: 256
  epochs: 100
  num_workers: 4
optimizer:
  lr: 3.0e-4
  weight_decay: 10.0e-6
