general:
  output_dir: ./results/resnet50/byol-affine/tiny_imagenet
network:
  algo: byol
  name: resnet50
  mlp_head:
    hidden_size: 512
    proj_size: 128
data:
  s: 1
  image_size: 64
  dataset: tiny_imagenet
  root: /home-mscluster/dtorpey/dataset/tiny-imagenet
  num_classes: 100
  dataset_type: affine
trainer:
  batch_size: 256
  epochs: 100
  num_workers: 4
optimizer:
  lr: 0.03
  weight_decay: 0.0004
